-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    C: in std_logic;
    B: in std_logic;
    A: in std_logic;
    C0: in std_logic;
    A0: in std_logic;
    Z: out std_logic;
    Y: out std_logic;
    Z0: out std_logic;
    Y0: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
begin
  s0 <= NOT C;
  s1 <= NOT B;
  s2 <= NOT A;
  s3 <= NOT C0;
  s4 <= NOT A0;
  Z <= ((s0 AND A) OR (C AND s2));
  Y <= ((s0 OR s2) AND (C OR A));
  Z0 <= ((A0 AND s3) OR (s4 AND C0));
  Y0 <= ((A0 AND s3) OR (s4 AND C0));
end Behavioral;
