-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity c8_BIN_a_XS3 is
  port (
    B3: in std_logic;
    B2: in std_logic;
    B1: in std_logic;
    B0: in std_logic;
    Y: out std_logic);
end c8_BIN_a_XS3;

architecture Behavioral of c8_BIN_a_XS3 is
begin
  Y <= ((NOT B0 AND NOT B2 AND NOT B3) OR (B0 AND B2 AND B3) OR (NOT B1 AND NOT B2 AND NOT B3) OR (B1 AND B2 AND B3));
end Behavioral;
