-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    B3: in std_logic;
    B2: in std_logic;
    B1: in std_logic;
    B0: in std_logic;
    BIT3: out std_logic;
    BIT2: out std_logic;
    BIT1: out std_logic;
    BIT0: out std_logic;
    bms_3: out std_logic;
    bms_2: out std_logic;
    bms_1: out std_logic;
    bms_0: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
begin
  BIT3 <= '0';
  BIT0 <= ((B1 AND B3) OR (B2 AND B3));
  s1 <= NOT B3;
  s0 <= NOT B1;
  bms_3 <= (s0 AND NOT B2 AND B3);
  bms_2 <= ((B1 AND B2) OR (B2 AND s1));
  bms_1 <= ((B1 AND s1) OR (s0 AND B2 AND B3));
  bms_0 <= B0;
end Behavioral;
