-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    C: in std_logic;
    B: in std_logic;
    A: in std_logic;
    Z: out std_logic);
end main;

architecture Behavioral of main is
begin
  Z <= ((C OR B) AND (NOT C OR NOT B OR NOT A));
end Behavioral;
