-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    A: in std_logic;
    B: in std_logic;
    C_IN: in std_logic;
    S: out std_logic;
    C_SAL: out std_logic);
end main;

architecture Behavioral of main is
begin
  S <= (A XOR (B XOR C_IN));
  C_SAL <= ((B AND C_IN) OR (B AND A) OR (C_IN AND A));
end Behavioral;
